# Generated by Django 5.0.7 on 2024-08-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComandStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='dastlabki text: ')),
                ('discreiption', models.TextField()),
                ('image', models.ImageField(upload_to='Rasm')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asosiy sahifa',
            },
        ),
        migrations.CreateModel(
            name='Menyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taom_turi', models.CharField(max_length=30, verbose_name='taam turi')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Taomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30, verbose_name='nomini kiriting: ')),
                ('narxi', models.BigIntegerField(verbose_name='narxi: ')),
                ('rasm', models.ImageField(upload_to='taomlar/rasm', verbose_name='taom rasmi: ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('taom_tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.menyu')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
            },
        ),
    ]
